const app=document.querySelector('#app');
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let token=localStorage.getItem('media-token')||'',teacher=sessionStorage.getItem('media-teacher')||'',state=null,selected={},feedback=null,busy=false,poll=null;
const admin=location.pathname==='/admin';
function error(e){const n=document.querySelector('#notice');n.textContent=e.message||e;n.style.display='block';setTimeout(()=>n.style.display='none',6000)}
async function api(path,body){const r=await fetch(path,{method:body?'POST':'GET',headers:{'Content-Type':'application/json','Authorization':token,'X-Teacher-Key':admin?teacher:''},...(body?{body:JSON.stringify(body)}:{})});const d=await r.json();if(!r.ok)throw Error(d.error||'เชื่อมต่อไม่สำเร็จ');return d}
function bind(id,fn){const e=document.getElementById(id);if(e)e.onclick=fn}
document.getElementById('motion').onclick=()=>{window.mediaMotionPaused=!window.mediaMotionPaused;document.getElementById('motion').textContent=window.mediaMotionPaused?'เปิดภาพเคลื่อนไหว':'หยุดภาพเคลื่อนไหว'};
document.getElementById('close-cards').onclick=()=>document.getElementById('cards').close();
function cards(){document.getElementById('card-content').innerHTML=state.cards.map(c=>`<article class="law"><h3>${esc(c.title)}</h3><p>${esc(c.text)}</p><p class="small muted">${esc(c.law)}</p></article>`).join('');document.getElementById('cards').showModal()}
function start(){app.innerHTML=`<section class="start"><div class="intro"><div class="eyebrow">COMMUNICATION ARTS / YEAR 03</div><h1>ทุกการตัดสินใจ<br>มี<span>กฎหมาย</span><br>อยู่เบื้องหลัง</h1><p class="muted">รับบทคนทำสื่อ ผ่านภารกิจสั้น ๆ ตั้งแต่แยกประเภทสื่อ<br>ไปจนถึงวันที่ผลงานของคุณพร้อมเผยแพร่</p><div class="chips"><span class="chip">30–45 นาที</span><span class="chip">15 ภารกิจ</span><span class="chip">10 คะแนน</span></div><p class="small muted">เรียนตาม พ.ร.บ. 2551 และสไลด์ที่อาจารย์กำหนด<br>เปิดการ์ดกฎหมายได้ ไม่หักคะแนน • ไม่มีโบนัสความเร็ว</p></div><form class="panel" id="join"><div class="eyebrow">ENTER THE MISSION</div><h2>เข้าห้องเรียน</h2><label for="room">รหัสห้องจากอาจารย์</label><input id="room" name="room" placeholder="เช่น A1B2C3" required maxlength="6" autocomplete="off"><label for="student">รหัสนักศึกษา</label><input id="student" name="student" required maxlength="40" autocomplete="off"><label for="nickname">ชื่อเล่นบนตารางอันดับ</label><input id="nickname" name="nickname" required maxlength="32"><button class="primary">เข้าร่วมภารกิจ →</button><p class="small muted">รหัสนักศึกษาและคะแนนวิชาเห็นเฉพาะคุณและอาจารย์ อันดับแสดงชื่อเล่น</p><details class="recovery"><summary>กลับเข้าเกมด้วยรหัสกู้คืน</summary><input id="recover-token" aria-label="รหัสกู้คืน"><button type="button" id="recover">กู้คืนเกม</button></details></form></section>`;
 document.getElementById('join').onsubmit=async e=>{e.preventDefault();const btn=e.target.querySelector('button');btn.disabled=true;try{const d=await api('/api/join',Object.fromEntries(new FormData(e.target)));token=d.token;localStorage.setItem('media-token',token);await refresh(true)}catch(e){error(e)}finally{btn.disabled=false}};
 bind('recover',async()=>{token=document.getElementById('recover-token').value.trim();localStorage.setItem('media-token',token);try{await refresh(true)}catch(e){error(e)}})
}
function board(){return `<aside class="panel"><div class="eyebrow">CLASS LEADERBOARD</div><h3>อันดับในห้อง</h3><p class="small muted">ตอบถูกครั้งแรกในช่วงฝึก +150<br>ลองใหม่จนผ่าน +100<br>ประเมิน +100 ต่อส่วนที่ถูก<br>คะแนนเท่ากัน อันดับร่วมกัน</p><div id="ranks">${state.leaderboard.map(x=>`<div class="rankrow"><span>${x.rank}</span><span>${esc(x.nickname)}</span><strong>${x.xp}</strong></div>`).join('')}</div>${!state.released?'<p class="small muted">คะแนนประเมินจะรวมในอันดับเมื่อเปิดเฉลย</p>':''}</aside>`}
function render(){if(!state)return;const s=state;
 if(s.state==='lobby'){app.innerHTML=`<section class="workspace wait panel center"><div class="eyebrow">READY WHEN YOU ARE</div><h1>พร้อมแล้ว ${esc(s.nickname)}</h1><p>ห้อง <strong class="room-code">${esc(s.room)}</strong></p><p class="muted">รออาจารย์เริ่มรอบ ทุกคนจะเริ่มพร้อมกัน</p><button id="card-button">อ่านการ์ดกฎหมายระหว่างรอ</button><p class="small muted">ใช้เครื่องและเบราว์เซอร์เดิมเพื่อกลับเข้าเกมได้</p></section>`;bind('card-button',cards);return}
 const top=`<div class="topline"><div><span class="eyebrow">ROOM ${esc(s.room)}</span><div>${esc(s.nickname)} · <span class="stat">${s.xp} XP</span></div></div><div class="inline"><span class="timer" id="timer"></span><button id="card-button">▤ การ์ดกฎหมาย</button></div></div>`;
 if(s.done||s.released){app.innerHTML=`<section class="workspace">${top}<div class="layout"><div class="panel"><div class="eyebrow">MISSION ${s.done?'COMPLETE':'CLOSED'}</div><h2>${s.released?'ผลการเรียนรู้ของคุณ':'ส่งภารกิจครบแล้ว'}</h2>${s.released?`<div class="score">${s.score}<small> / 10</small></div><p>รหัสนักศึกษา ${esc(s.student)} · ${esc(s.nickname)}</p><p class="muted">ระบบกลางบันทึกคะแนนแล้ว${!s.done?' ข้อที่ยังไม่ตอบคิดเป็น 0 คะแนน':''}</p><a class="button primary" href="${esc(s.forms)}" target="_blank" rel="noopener noreferrer">ส่งคะแนนให้อาจารย์ผ่าน Microsoft Forms ↗</a><p class="small muted">ฟอร์มจะกรอกข้อมูลให้ล่วงหน้า โปรดตรวจสอบแล้วกดส่งใน Forms อีกครั้ง</p><h3>ทบทวนภารกิจประเมิน</h3>${s.review.map(q=>`<details class="review"><summary>${esc(q.title)} · ${q.earned}/2</summary><p>${esc(q.action)}</p><p>${esc(q.reason)}</p><p class="muted">${esc(q.why)}</p><small>${esc(q.law)}</small></details>`).join('')}`:'<p>รอเพื่อนส่งครบ อาจารย์ปิดรอบ หรือหมดเวลา จึงจะแสดงคะแนนและเฉลยพร้อมกัน</p><p class="muted">คุณสามารถเปิดการ์ดกฎหมายทบทวนระหว่างรอได้</p>'}</div>${board()}</div></section>`;bind('card-button',cards);tick();return}
 const q=s.question;if(!q)return;
 app.innerHTML=`<section class="workspace">${top}<div class="progress"><div style="width:${s.index/s.total*100}%"></div></div><div class="layout"><article class="panel"><div class="topline"><span class="eyebrow">${esc(q.phase)} / ${s.index+1} OF ${s.total}</span><span class="role">${esc(q.role)}</span></div><h2>${esc(q.title)}</h2><p class="scenario">${esc(q.story)}</p>${q.phase==='นิยาม'?'<p class="small muted">เริ่มจากมาตรา 4 · เปิดการ์ด 01 ก่อนตอบได้ ต้องตอบถูกทั้งสองขั้นจึงผ่าน</p>':''}${q.phase==='ประเมิน'?'<p class="small muted">ข้อละ 2 คะแนน · บันทึกคำตอบครั้งแรก แก้ไขไม่ได้หลังส่ง · เฉลยเมื่อจบรอบ</p>':''}<div class="step-label">01 / คุณจะตัดสินใจอย่างไร?</div><div class="options">${q.actions.map((o,i)=>option(o,i,'action')).join('')}</div><div class="step-label">02 / หลักกฎหมายใดสนับสนุน?</div><div class="options">${q.reasons.map((o,i)=>option(o,i,'reason')).join('')}</div><div class="actions"><button class="primary" id="answer" ${selected.action===undefined||selected.reason===undefined?'disabled':''}>${q.phase==='ประเมิน'?'ยืนยันคำตอบและบันทึก':'ตรวจคำตอบ'} →</button></div>${feedback?`<div class="feedback ${feedback.advance?'':'bad'}" role="status"><strong>การตัดสินใจ ${feedback.actionCorrect?'✓ ถูก':'ยังไม่ถูก'} · เหตุผล ${feedback.reasonCorrect?'✓ ถูก':'ยังไม่ถูก'}</strong><p>${esc(feedback.why)}</p><p class="small muted">${esc(feedback.law)}</p>${feedback.advance?`<button class="primary" id="next">ภารกิจถัดไป →</button>`:'<p>เลือกใหม่ แล้วตรวจคำตอบอีกครั้งได้</p>'}</div>`:''}</article>${board()}</div><footer>อ้างอิงเอกสารที่กำหนดในชั้นเรียน ไม่ใช่การยืนยันสถานะกฎหมายปัจจุบัน</footer></section>`;
 bind('card-button',cards);document.querySelectorAll('[data-option]').forEach(el=>el.onclick=()=>{if(feedback?.advance)return;selected[el.dataset.kind]=Number(el.dataset.option);render()});
 bind('answer',submit);bind('next',async()=>{feedback=null;selected={};await refresh(true)});if(feedback?.advance)document.getElementById('answer').disabled=true;tick()
}
function option(o,i,kind){return `<button class="option ${selected[kind]===o.id?'selected':''}" data-option="${o.id}" data-kind="${kind}" aria-pressed="${selected[kind]===o.id}"><span class="letter">${String.fromCharCode(65+i)}</span><span>${esc(o.text)}</span></button>`}
async function submit(){if(busy)return;busy=true;document.getElementById('answer').disabled=true;try{const d=await api('/api/answer',{id:state.question.id,...selected});if(state.question.phase==='ประเมิน'){selected={};feedback=null;await refresh(true)}else{feedback=d;render()}}catch(e){error(e);await refresh(true)}finally{busy=false}}
async function refresh(force=false){if(!token)return;const old=state;const next=await api('/api/state');if(feedback?.advance&&!force&&next.state!=='closed'&&!next.released)return;state=next;if(force||!old||old.state!==next.state||old.index!==next.index||old.released!==next.released){if(!feedback?.advance||next.released)render()}else{const ranks=document.querySelector('#ranks');if(ranks)ranks.innerHTML=next.leaderboard.map(x=>`<div class="rankrow"><span>${x.rank}</span><span>${esc(x.nickname)}</span><strong>${x.xp}</strong></div>`).join('')}}
function tick(){const e=document.getElementById('timer');if(!e||!state)return;const t=Math.max(0,Math.ceil(state.deadline-Date.now()/1000));e.textContent=state.state==='closed'?'ปิดรอบแล้ว':`เวลาที่เหลือ ${Math.floor(t/60)}:${String(t%60).padStart(2,'0')}`}
function adminLogin(){app.innerHTML=`<section class="workspace wait panel"><div class="eyebrow">INSTRUCTOR CONSOLE</div><h2>จัดการห้องเรียน</h2><p class="muted">ใช้รหัสอาจารย์ที่ตั้งไว้ในระบบโฮสต์ (TEACHER_KEY)</p><form id="admin-login"><label for="key">รหัสอาจารย์</label><input id="key" type="password" required autocomplete="current-password"><button class="primary">เข้าสู่ระบบ</button></form></section>`;document.getElementById('admin-login').onsubmit=async e=>{e.preventDefault();teacher=document.getElementById('key').value;try{await adminRefresh();sessionStorage.setItem('media-teacher',teacher)}catch(e){error(e)}}}
async function adminRefresh(){const d=await api('/api/admin');app.innerHTML=`<section class="workspace"><div class="topline"><div><div class="eyebrow">INSTRUCTOR CONSOLE</div><h1>ห้องเรียนของคุณ</h1></div><div class="actions"><button id="create" class="primary">+ สร้างห้องใหม่</button><button id="export">ดาวน์โหลดคะแนน CSV</button></div></div><p class="muted">ให้นักศึกษาเข้าครบก่อนกดเริ่ม เมื่อเริ่มแล้วจะปิดรับคนเพิ่ม • คะแนนรายวิชาคำนวณที่แม่ข่าย</p>${d.rooms.map(r=>`<div class="panel room"><div class="topline"><span class="room-code">${esc(r.code)}</span><span>${({lobby:'รอผู้เล่น',playing:'กำลังเล่น',closed:'ปิดรอบแล้ว'})[r.state]}</span></div><div class="inline"><select aria-label="เวลาเล่น" id="minutes-${r.code}"><option value="40">40 นาที</option><option value="30">30 นาที</option><option value="45">45 นาที</option></select><button data-start="${r.code}" ${r.state!=='lobby'?'disabled':''}>เริ่มพร้อมกัน</button><button data-close="${r.code}" ${r.state==='closed'?'disabled':''}>ปิดรอบและเปิดเฉลย</button></div><div class="table-wrap"><table><thead><tr><th>รหัสนักศึกษา</th><th>ชื่อเล่น</th><th>ภารกิจ</th><th>XP</th><th>คะแนน /10</th><th>กู้คืน</th></tr></thead><tbody>${d.players.filter(p=>p.room===r.code).map(p=>`<tr><td>${esc(p.student)}</td><td>${esc(p.nickname)}</td><td>${p.idx}/15</td><td>${p.xp}</td><td>${p.score}</td><td><button data-recover-room="${r.code}" data-student="${esc(p.student)}">ออกรหัสกู้คืน</button></td></tr>`).join('')}</tbody></table></div></div>`).join('')}<button id="admin-refresh">อัปเดตสถานะ</button><p class="small muted">ตรวจชื่อและรหัสนักศึกษากับรายชื่อในชั้นเรียน ระบบนี้ยังไม่มีการเข้าสู่ระบบด้วยบัญชีมหาวิทยาลัย</p><p class="small muted">หมายเหตุเนื้อหา: สไลด์ 41 สรุปเรื่องโรงกลางแจ้งคลาดเคลื่อน เกมยึดมาตรา 37 ในตัวบท</p></section>`;
 bind('create',async()=>{try{await api('/api/admin/create',{});await adminRefresh()}catch(e){error(e)}});bind('admin-refresh',()=>adminRefresh().catch(error));
 document.querySelectorAll('[data-start]').forEach(e=>e.onclick=async()=>{try{await api('/api/admin/start',{room:e.dataset.start,minutes:Number(document.getElementById('minutes-'+e.dataset.start).value)});await adminRefresh()}catch(e){error(e)}});
 document.querySelectorAll('[data-close]').forEach(e=>e.onclick=async()=>{if(!confirm('ปิดรอบนี้และเปิดเฉลย? คำตอบที่ยังไม่ส่งจะได้ 0 คะแนน'))return;try{await api('/api/admin/close',{room:e.dataset.close});await adminRefresh()}catch(e){error(e)}});
 document.querySelectorAll('[data-recover-room]').forEach(e=>e.onclick=async()=>{try{const d=await api('/api/admin/recover',{room:e.dataset.recoverRoom,student:e.dataset.student});prompt('ส่งรหัสนี้ให้เจ้าของรหัสนักศึกษาเท่านั้น (เครื่องเดิมจะออกจากระบบ)',d.token)}catch(e){error(e)}});
 bind('export',async()=>{try{const r=await fetch('/api/export',{headers:{'X-Teacher-Key':teacher}});if(!r.ok)throw Error('ดาวน์โหลดไม่สำเร็จ');const u=URL.createObjectURL(await r.blob());const a=document.createElement('a');a.href=u;a.download='media-mission-scores.csv';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}catch(e){error(e)}})
}
if(admin){if(teacher)adminRefresh().catch(()=>adminLogin());else adminLogin()}else{if(token)refresh(true).catch(()=>{token='';localStorage.removeItem('media-token');start()});else start();poll=setInterval(()=>refresh().catch(error),5000);setInterval(tick,1000)}
