const app=document.getElementById('app'),{cards,questions}=GAME_CONTENT,E=GameEngine,STORE='media-mission-pages-v1';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let game=null,selected={},feedback=null,shown=null;
function notice(message){const e=document.getElementById('notice');e.textContent=message;e.style.display='block';setTimeout(()=>e.style.display='none',6000)}
function save(){try{localStorage.setItem(STORE,JSON.stringify(game))}catch(e){notice('เบราว์เซอร์บันทึกความคืบหน้าไม่ได้ กรุณาอย่าปิดหน้านี้ระหว่างเล่น')}}
try{const raw=JSON.parse(localStorage.getItem(STORE));if(raw&&raw.version===1&&Number.isInteger(raw.index)&&raw.index>=0&&raw.index<=questions.length&&Number.isFinite(raw.deadline)&&raw.attempts&&Array.isArray(raw.answers))game=raw;}catch(e){}
function bind(id,fn){const e=document.getElementById(id);if(e)e.onclick=fn}
bind('motion',()=>{window.mediaMotionPaused=!window.mediaMotionPaused;document.getElementById('motion').textContent=window.mediaMotionPaused?'เปิดภาพเคลื่อนไหว':'หยุดภาพเคลื่อนไหว'});
bind('close-cards',()=>document.getElementById('cards').close());
function openCards(){document.getElementById('card-content').innerHTML=cards.map(c=>`<article class="law"><h3>${esc(c.title)}</h3><p>${esc(c.text)}</p><p class="small muted">${esc(c.law)}</p></article>`).join('');document.getElementById('cards').showModal()}
function start(){app.innerHTML=`<section class="start"><div><div class="eyebrow">MEDIA MISSION / PAGES EDITION</div><h1>ทุกการตัดสินใจ<br>มี<span>กฎหมาย</span><br>อยู่เบื้องหลัง</h1><p class="muted">สลับบทบาทคนทำสื่อ เรียนรู้ผ่านสถานการณ์<br>ตั้งแต่แยกประเภทสื่อไปจนถึงการเผยแพร่</p><div class="chips"><span class="chip">40 นาที</span><span class="chip">15 ภารกิจ</span><span class="chip">10 คะแนน</span></div><p class="small muted">เปิดการ์ดกฎหมายได้ • ไม่มีโบนัสความเร็ว<br>เรียนตาม พ.ร.บ. 2551 และเอกสารที่อาจารย์กำหนด</p></div><form id="join" class="panel"><div class="eyebrow">YOUR NEXT MISSION</div><h2>พร้อมเริ่มภารกิจ?</h2><label for="student">รหัสนักศึกษา</label><input id="student" name="student" required maxlength="40"><label for="nickname">ชื่อเล่น</label><input id="nickname" name="nickname" required maxlength="32"><p class="small muted">ไม่ต้องใช้รหัสห้อง เริ่มเมื่ออาจารย์แจ้ง<br>เวลาเริ่มนับเมื่อกดปุ่มและยังเดินต่อแม้ปิดหน้า</p><button class="primary">เริ่มภารกิจ →</button><p class="small muted">ความคืบหน้าเก็บในเบราว์เซอร์นี้ เมื่อจบให้ส่งคะแนนผ่าน Microsoft Forms</p></form></section>`;document.getElementById('join').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target),student=f.get('student').trim(),nickname=f.get('nickname').trim();if(!student||!nickname)return;game=E.create(student,nickname);save();render()}}
function sidebar(){return `<aside class="panel"><div class="eyebrow">MISSION LOG</div><h3>เส้นทางการเรียนรู้</h3><div class="rankrow">01 · แยกประเภทสื่อ <span>4 ข้อ</span></div><div class="rankrow">02 · ฝึกตัดสินใจ <span>6 ข้อ</span></div><div class="rankrow">03 · ประเมิน <span>5 ข้อ</span></div><p class="small muted">ช่วงฝึก: ถูกครั้งแรก 150 XP<br>ลองใหม่จนผ่าน 100 XP<br>ประเมิน: ส่วนที่ถูก 100 XP</p><p class="small muted">คะแนนวิชาเต็ม 10 คะแนน มาจากภารกิจประเมินเท่านั้น</p><button id="card-side">เปิดการ์ดกฎหมาย</button><p class="small muted">อาจารย์รวบรวมคะแนนจาก Forms ไม่มีตารางอันดับร่วมกันในเว็บนี้</p></aside>`}
function top(){return `<div class="topline"><div><span class="eyebrow">${esc(game.nickname)}</span><div>${esc(game.student)} · <span class="stat">${game.done?game.xp:game.xp-game.score*100} XP</span></div></div><div class="inline"><span id="timer" class="timer"></span><button id="card-button">▤ การ์ดกฎหมาย</button></div></div>`}
function render(){if(!game)return start();if(E.expire(game))save();if(game.done)return finish();const q=feedback?.advance?shown:questions[game.index];shown=q;
app.innerHTML=`<section class="workspace">${top()}<div class="progress"><div style="width:${game.index/questions.length*100}%"></div></div><div class="layout"><article class="panel"><div class="topline"><span class="eyebrow">${esc(q.phase)} / ${questions.indexOf(q)+1} OF 15</span><span class="role">${esc(q.role)}</span></div><h2>${esc(q.title)}</h2><p class="scenario">${esc(q.story)}</p>${q.phase==='นิยาม'?'<p class="small muted">เปิดการ์ด 01 อ่านนิยามมาตรา 4 ก่อนตอบได้ ตอบถูกทั้งสองขั้นจึงผ่าน</p>':''}${q.phase==='ประเมิน'?'<p class="small muted">ข้อละ 2 คะแนน บันทึกครั้งแรกที่กดส่ง แก้ไขไม่ได้ และเฉลยหลังส่งครบหรือหมดเวลา</p>':''}<div class="step-label">01 / คุณจะตัดสินใจอย่างไร?</div><div class="options">${options(q.actions,'action',q)}</div><div class="step-label">02 / หลักกฎหมายใดสนับสนุน?</div><div class="options">${options(q.reasons,'reason',q)}</div><div class="actions"><button class="primary" id="answer" ${selected.action===undefined||selected.reason===undefined||feedback?.advance?'disabled':''}>${q.phase==='ประเมิน'?'ยืนยันและบันทึกคำตอบ':'ตรวจคำตอบ'} →</button></div>${feedback?`<div class="feedback ${feedback.advance?'':'bad'}" role="status"><strong>การตัดสินใจ ${feedback.actionCorrect?'✓ ถูก':'ยังไม่ถูก'} · เหตุผล ${feedback.reasonCorrect?'✓ ถูก':'ยังไม่ถูก'}</strong><p>${esc(feedback.why)}</p><p class="small muted">${esc(cards[feedback.card].law)}</p>${feedback.advance?'<button class="primary" id="next">ภารกิจถัดไป →</button>':'<p>ลองเลือกใหม่ แล้วตรวจคำตอบอีกครั้งได้</p>'}</div>`:''}</article>${sidebar()}</div><footer>เนื้อหาอ้างอิงเอกสารในชั้นเรียน ไม่ใช่การยืนยันสถานะกฎหมายปัจจุบัน</footer></section>`;
document.querySelectorAll('[data-option]').forEach(el=>el.onclick=()=>{if(feedback?.advance)return;selected[el.dataset.kind]=Number(el.dataset.option);render()});bind('answer',()=>{try{const result=E.answer(game,q.id,selected.action,selected.reason);save();if(q.phase==='ประเมิน'){feedback=null;selected={}}else feedback=result;render()}catch(e){notice(e.message);render()}});bind('next',()=>{feedback=null;selected={};render()});bindCards();tick()}
function options(list,kind,q){return list.map((text,id)=>({text,id,order:hash(game.student+q.id+kind+id)})).sort((a,b)=>a.order-b.order).map((o,i)=>`<button class="option ${selected[kind]===o.id?'selected':''}" data-kind="${kind}" data-option="${o.id}" aria-pressed="${selected[kind]===o.id}"><span class="letter">${String.fromCharCode(65+i)}</span><span>${esc(o.text)}</span></button>`).join('')}
function hash(s){let h=0;for(const c of s)h=(h*31+c.charCodeAt(0))>>>0;return h}
function bindCards(){bind('card-button',openCards);bind('card-side',openCards)}
function finish(){app.innerHTML=`<section class="workspace">${top()}<div class="layout"><article class="panel"><div class="eyebrow">MISSION COMPLETE</div><h2>${game.index===15?'จบภารกิจแล้ว':'หมดเวลาแล้ว'}</h2><div class="score">${game.score}<small> / 10</small></div><p>รหัสนักศึกษา ${esc(game.student)} · ${esc(game.nickname)}</p><p class="muted">คะแนนนี้บันทึกในเบราว์เซอร์ของคุณ ยังไม่ได้ส่งให้อาจารย์${game.index<15?' ข้อประเมินที่ยังไม่ส่งได้ 0 คะแนน':''}</p><a class="button primary" href="${esc(E.forms(game))}" target="_blank" rel="noopener noreferrer">ส่งคะแนนให้อาจารย์ผ่าน Microsoft Forms ↗</a><p class="small muted">ฟอร์มจะกรอกข้อมูลล่วงหน้า ตรวจสอบและกดส่งใน Forms อีกครั้ง เว็บนี้ไม่สามารถตรวจสอบสถานะการส่งของ Forms ได้</p><h3>เฉลยภารกิจประเมิน</h3>${questions.filter(q=>q.phase==='ประเมิน').map(q=>{const a=game.answers.find(x=>x.id===q.id);return `<details class="review"><summary>${esc(q.title)} · ${a?.points||0}/2</summary><p>${esc(q.actions[q.correct[0]])}</p><p>${esc(q.reasons[q.correct[1]])}</p><p>${esc(q.why)}</p><p class="small muted">${esc(cards[q.card].law)}</p></details>`}).join('')}<hr><button id="reset">เริ่มรอบใหม่ / เปลี่ยนผู้เล่น</button><p class="small muted">เริ่มรอบใหม่จะล้างคะแนนในเบราว์เซอร์นี้ ส่ง Forms ให้เรียบร้อยก่อน</p></article>${sidebar()}</div></section>`;bindCards();bind('reset',()=>{if(!confirm('ล้างผลในเครื่องและเริ่มใหม่? โปรดส่งคะแนนผ่าน Forms ก่อน'))return;game=null;feedback=null;selected={};try{localStorage.removeItem(STORE)}catch(e){}start()});tick()}
function tick(){if(!game)return;const e=document.getElementById('timer');if(e){const sec=Math.max(0,Math.ceil((game.deadline-Date.now())/1000));e.textContent=game.done?'จบรอบแล้ว':`เหลือ ${Math.floor(sec/60)}:${String(sec%60).padStart(2,'0')}`;}if(!game.done&&E.expire(game)){save();render()}}
setInterval(tick,1000);render();
